import type { Metadata } from 'next'
import './globals.css'
import Navigation from './_components/Global/Navigation'
import Footer from './_components/Global/Footer'

export const metadata: Metadata = {
    title: {
        template: '%s | Solárium Avantgarda Olomouc',
        default: 'Solárium Avantgarda Olomouc',
    },
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='cs'>
            <body className={`antialiased flex flex-col items-center`}>
                <Navigation></Navigation>

                <main className='max-w-[1392px] w-full px-5'>{children}</main>

                <Footer></Footer>
            </body>
        </html>
    )
}
