import { Metadata } from 'next'
import Hero from './_components/MainPage/Sections/Hero'
import FindUs from './_components/MainPage/Sections/FindUs'
import QaA from './_components/MainPage/Sections/QaA'

export const metadata: Metadata = {
    title: 'Úvod',
    description: 'Generated by create next app',
}

export default function Home() {
    return (
        <div>
            <Hero></Hero>
            <FindUs></FindUs>
            <QaA></QaA>
        </div>
    )
}
