import { Metadata } from 'next'
import Hero from './_components/MainPage/Sections/Hero'
import FindUs from './_components/MainPage/Sections/FindUs'
import QaA from './_components/MainPage/Sections/QaA'
import AboutUs from './_components/MainPage/Sections/AboutUs'
import Cabbins from './_components/MainPage/Sections/Cabbins'

export const metadata: Metadata = {
    title: 'Úvod | Solárium Avantgarda Olomouc',
    description: 'Generated by create next app',
}

export default function Home() {
    return (
        <div className='flex flex-col gap-10'>
            <Hero></Hero>
            <AboutUs></AboutUs>
            <Cabbins></Cabbins>
            <FindUs></FindUs>
            <QaA></QaA>
        </div>
    )
}
